### ISSUE TITLE
Change/update documentation quote on website

### ISSUE THREAD

**Issue by jjojohjohnflowers** [helio-fm/muse-hackers#2]
Please change or remove the quote at the bottom of your home page comparing documentation to sex. I find it problematic, and I am sure many of your potential users would be turned away by it as well.

Also consider that your audience may have had bad experiences with sex, and may not want to be reminded of it when using/browsing music software.

Are there other quotes that express the same sentiment without bringing sex into it?

**Comment by peterrudenko** [comment]
First, thank you for asking that in a polite manner, unlike https://github.com/helio-fm/helio-workstation/discussions/207 does.

As much as this request rubs me the wrong way for some reason, I guess you're right. Seemingly the project is getting more attention than I expected, so someday this quote would have to be replaced with something more korrekt. Growing up is no fun.

**Comment by jjojohjohnflowers** [comment]
Thank you for understanding!

btw, I definitely understand the sentiment that the quote is aiming for (that bad documentation is better than no documentation), I just think that sex is such a loaded and sensitive topic and I'd hate if that quote distracted from the software itself.

**Comment by jjojohjohnflowers** [comment]
Was just reading that forum thread, in particular your response

> "Look, I'm a smol indie project, maintained by one hobbyist musician in his spare time, with unfinished parts here and there, and docs being far from perfection."

Could you perhaps somewhere bring attention to the fact that the documentation is incomplete and it needs volunteers to help complete it? Could be posted on the docs page or on the front page.

Either way, thanks again for changing it :-)
